Repository FOSSRIT/people, pull requests merged in 2020-04, with the labels that each got.

#82 gitignore: Cover more tools and editors
  .gitignore
Labels: contributor experience, new change

#81 ci: Add Travis config and Rakefile with html-proofer
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
  _config.yaml
Labels: new change, quality assurance

#83 Fix 404 URLs on two profiles
  _data/alum/nikkonikko.yaml
  _data/faculty/deejoe.yaml
Labels: bug, profile update

#80 Move jwf from Students -> Alums
  _data/alum/jwf.yaml
  _data/student/jflory7.yaml
Labels: improvement, profile update

#79 Move callahad and threebean to alums
  _data/alum/callahad.yaml
  _data/alum/threebean.yaml
Labels: improvement, profile update

#84 ci: Deploy built site from Travis
  .travis.yml
Labels: new change, quality assurance

#85 config: Expand excludes, set permalink to pretty
  _config.yaml
Labels: improvement

#86 config: Set baseurl to `people` for CSS to render
  Rakefile
  _config.yaml
Labels: bug

#88 docs: Fix broken links, improve contribution guide (fixes #87)
  .github/CONTRIBUTING.md
  README.md
Labels: bug, documentation

#89 creating profile
  _data/student/galluccioProfile.yaml
Labels: new profile

#90 Update ctmartin.yaml
  _data/student/ctmartin.yaml
Labels: improvement, profile update

#91 workflows: Add inclusive-organization-action@v1.1.0
  .github/workflows/invite-to-fossrit.yml
Labels: contributor experience, new change
